name: Lint Go

on:
  pull_request:

env:
  SRC_DIR: src

jobs:
  lint:
    ### Multiple OS linting strategy
    #strategy:
    #  matrix:
    #    go-version: [1.15.x]
    #    os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ubuntu-latest #${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Override ENV
      uses: c-py/action-dotenv-to-setenv@v3
      continue-on-error: true

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.38
        working-directory: ${{ env.SRC_DIR }}

        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        # only-new-issues: true

        # Optional: if set to true then the action will use pre-installed Go.
        # skip-go-installation: true

        # Optional: if set to true then the action don't cache or restore ~/go/pkg.
        # skip-pkg-cache: true

        # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
        # skip-build-cache: true
